
CREATE TABLE `sensors` (
   `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   `pin_number` VARCHAR(2) NOT NULL,
   `name` VARCHAR(255) NOT NULL,
   `location_desciption` VARCHAR(255) NULL DEFAULT NULL
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `sensor_datas` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `sensor_id`INT NOT NULL,
    `frequency` INT UNSIGNED NOT NULL DEFAULT 0,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT `fk_sensor_datas_sensors` FOREIGN KEY(`sensor_id`) REFERENCES `sensors`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;